# Generated by Django 4.2.6 on 2023-10-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                ("mat_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=255)),
                ("synonyms", models.TextField(max_length=255)),
                ("chem_form", models.TextField(max_length=255)),
                ("cas_num", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Nanoparticle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("np_str", models.TextField(max_length=255)),
                ("size", models.FloatField()),
                ("article_id", models.IntegerField()),
                (
                    "mat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labdata.material",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=255)),
                ("email", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Synthesis",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("method", models.TextField(max_length=255)),
                ("article_id", models.IntegerField()),
                (
                    "np",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labdata.nanoparticle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nova",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("method", models.TextField(max_length=255)),
                ("absorbat", models.TextField(max_length=255)),
                ("pore_size", models.FloatField()),
                ("density", models.FloatField()),
                ("ads_desorb_curve", models.FileField(upload_to="")),
                ("pore_distr_curve", models.FileField(upload_to="")),
                (
                    "np",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labdata.nanoparticle",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="nanoparticle",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="labdata.user"
            ),
        ),
    ]
