# Generated by Django 4.2.6 on 2023-10-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("labdata", "0002_user_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("art_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="nanoparticle",
            name="article_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="labdata.article"
            ),
        ),
    ]
